const mongoose = require('mongoose');
const Recipe = require('./models/Recipe');
const connectDB = require('./config/db');
require('dotenv').config();

const recipes = [
  {
    _id: new mongoose.Types.ObjectId('000000000000000000000001'),
    name: 'Spicy Thai Basil Chicken',
    ingredients: [
      { name: 'chicken breast', quantity: '300g' },
      { name: 'thai basil leaves', quantity: '1 cup' },
      { name: 'garlic', quantity: '4 cloves' },
      { name: 'chili peppers', quantity: '2 pieces' },
      { name: 'fish sauce', quantity: '2 tbsp' },
      { name: 'soy sauce', quantity: '1 tbsp' },
    ],
    instructions: [
      'Heat oil in a wok over high heat',
      'Add garlic and chili, stir-fry for 30 seconds',
      'Add chicken and cook until golden',
      'Add sauces and stir-fry for 2 minutes',
      'Add basil leaves and cook for 1 minute',
      'Serve hot with steamed rice',
    ],
    prepTime: 20,
    difficulty: 'medium',
    tags: ['thai', 'spicy', 'quick'],
    imageUrl: 'https://images.unsplash.com/photo-1707897634981-39bcfe435268?q=80&w=898&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    _id: new mongoose.Types.ObjectId('000000000000000000000002'),
    name: 'Creamy Mushroom Risotto',
    ingredients: [
      { name: 'arborio rice', quantity: '1 cup' },
      { name: 'mixed mushrooms', quantity: '200g' },
      { name: 'onion', quantity: '1 medium' },
      { name: 'white wine', quantity: '1/2 cup' },
      { name: 'vegetable stock', quantity: '3 cups' },
      { name: 'parmesan cheese', quantity: '1/2 cup' },
    ],
    instructions: [
      'Sauté mushrooms until golden, set aside',
      'Cook onion until translucent',
      'Add rice and stir for 2 minutes',
      'Add wine and stir until absorbed',
      'Add stock gradually, stirring constantly',
      'Fold in mushrooms and parmesan',
    ],
    prepTime: 35,
    difficulty: 'medium',
    tags: ['italian', 'vegetarian', 'comfort-food'],
    imageUrl: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?auto=format&fit=crop&w=800&h=600',
  },
  {
    _id: new mongoose.Types.ObjectId('000000000000000000000003'),
    name: 'Mediterranean Quinoa Bowl',
    ingredients: [
      { name: 'quinoa', quantity: '1 cup' },
      { name: 'cherry tomatoes', quantity: '1 cup' },
      { name: 'cucumber', quantity: '1 medium' },
      { name: 'feta cheese', quantity: '100g' },
      { name: 'olives', quantity: '1/2 cup' },
      { name: 'olive oil', quantity: '3 tbsp' },
    ],
    instructions: [
      'Cook quinoa according to package directions',
      'Chop tomatoes and cucumber into bite-sized pieces',
      'Mix vegetables with cooked quinoa',
      'Crumble feta cheese on top',
      'Add olives and drizzle with olive oil',
      'Season with salt and herbs',
    ],
    prepTime: 15,
    difficulty: 'easy',
    tags: ['mediterranean', 'healthy', 'vegetarian'],
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&h=600',
  },
  {
    _id: new mongoose.Types.ObjectId('000000000000000000000004'),
    name: 'Homemade Pasta Carbonara',
    ingredients: [
        { name: 'spaghetti', quantity: '400g' },
        { name: 'eggs', quantity: '4 large' },
        { name: 'pancetta', quantity: '200g' },
        { name: 'parmesan cheese', quantity: '100g' },
        { name: 'black pepper', quantity: '1 tsp' }
      ],
    instructions: [
      'Cook pasta in salted boiling water until al dente',
      'In a bowl, whisk eggs with grated Parmesan and black pepper',
      'Slice pancetta thinly and fry in a pan until crispy',
      'Drain pasta and mix with pancetta',
      'Pour egg mixture over pasta and toss',
      'Season with salt and pepper',
    ],
    prepTime: 25,
    difficulty: 'medium',
    tags: ['italian', 'pasta', 'comfort-food'],
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300&q=80',
  },
  {
    _id: new mongoose.Types.ObjectId('000000000000000000000005'),
    name: 'Korean BBQ Beef Bowl',
    ingredients: [
      { name: 'beef sirloin', quantity: '300g' },
      { name: 'kimchi', quantity: '1/2 cup' },
      { name: 'rice', quantity: '2 cups' },
      { name: 'gochujang', quantity: '2 tbsp' },
      { name: 'fresh rosemary', quantity: '1 tbsp' },
    ],
    instructions: [
      'Slice beef into thin strips',
      'Marinate in gochujang, soy sauce, and sesame oil',
      'Cook rice according to package directions',
      'Grill beef until tender',
      'Serve with rice and kimchi',
    ],
    prepTime: 30,
    difficulty: 'medium',
    tags: ['korean', 'bbq', 'beef'],
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=400&h=300',
  },
  {
    _id: new mongoose.Types.ObjectId('000000000000000000000006'),
    name: 'Vegan Buddha Bowl',
    ingredients: [
      { name: 'quinoa', quantity: '1 cup' },
      { name: 'sweet potato', quantity: '2 medium' },
      { name: 'kale', quantity: '2 cups' },
      { name: 'chickpeas', quantity: '1 can' },
      { name: 'avocado', quantity: '1 large' },
      { name: 'flour', quantity: '1/4 cup' },
    ],
    instructions: [
      'Cook quinoa according to package directions',
      'Roast sweet potato cubes until tender',
      'Massage kale with lemon and salt',
      'Roast chickpeas until crispy',
      'Make tahini dressing with lemon',
      'Assemble bowl with all ingredients',
      'Serve warm with ice cream',
    ],
    prepTime: 40,
    difficulty: 'easy',
    tags: ['vegan', 'healthy', 'bowl'],
    imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=400&h=300',
  },
  {
  _id: new mongoose.Types.ObjectId('000000000000000000000007'),
  name: 'Avocado Toast with Poached Egg',
  ingredients: [
    { name: 'avocado', quantity: '1 ripe' },
    { name: 'whole grain bread', quantity: '2 slices' },
    { name: 'egg', quantity: '1' },
    { name: 'lemon juice', quantity: '1 tsp' },
    { name: 'red pepper flakes', quantity: 'pinch' },
    { name: 'salt', quantity: 'to taste' },
  ],
  instructions: [
    'Toast the bread slices until golden',
    'Mash avocado with lemon juice and salt',
    'Spread avocado mixture on toast',
    'Poach egg and place on avocado toast',
    'Sprinkle with red pepper flakes',
    'Serve immediately',
  ],
  prepTime: 10,
  difficulty: 'easy',
  tags: ['breakfast', 'healthy', 'quick'],
  imageUrl: 'https://images.unsplash.com/photo-1536974471655-0466120eff7f?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1169',
},
{
  _id: new mongoose.Types.ObjectId('000000000000000000000008'),
  name: 'Classic Beef Burger',
  ingredients: [
    { name: 'ground beef', quantity: '400g' },
    { name: 'burger buns', quantity: '4' },
    { name: 'cheddar cheese', quantity: '4 slices' },
    { name: 'lettuce', quantity: '4 leaves' },
    { name: 'tomato', quantity: '1 sliced' },
    { name: 'mayonnaise', quantity: '4 tbsp' },
  ],
  instructions: [
    'Season ground beef and form into 4 patties',
    'Grill patties for 4-5 minutes per side',
    'Toast burger buns on grill',
    'Add cheese to patties in last minute of cooking',
    'Assemble with lettuce, tomato, and mayonnaise',
    'Serve with fries or salad',
  ],
  prepTime: 20,
  difficulty: 'medium',
  tags: ['burger', 'american', 'grilled'],
  imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=400&h=300',
},
{
  _id: new mongoose.Types.ObjectId('000000000000000000000009'),
  name: 'Mediterranean Chickpea Salad',
  ingredients: [
    { name: 'chickpeas', quantity: '1 can drained' },
    { name: 'cucumber', quantity: '1 diced' },
    { name: 'cherry tomatoes', quantity: '1 cup halved' },
    { name: 'red onion', quantity: '1/4 thinly sliced' },
    { name: 'feta cheese', quantity: '100g crumbled' },
    { name: 'olive oil', quantity: '3 tbsp' },
  ],
  instructions: [
    'In a large bowl, combine chickpeas, cucumber, tomatoes, and red onion',
    'Drizzle with olive oil and toss gently',
    'Add crumbled feta cheese on top',
    'Season with salt and pepper to taste',
    'Serve immediately or chill for 30 minutes',
  ],
  prepTime: 15,
  difficulty: 'easy',
  tags: ['salad', 'mediterranean', 'vegetarian'],
  imageUrl: 'https://plus.unsplash.com/premium_photo-1664392002995-4ee10b7f91e5?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=707',
},
{
  _id: new mongoose.Types.ObjectId('00000000000000000000000a'),
  name: 'Thai Green Curry with Tofu',
  ingredients: [
    { name: 'tofu', quantity: '300g cubed' },
    { name: 'green curry paste', quantity: '2 tbsp' },
    { name: 'coconut milk', quantity: '400ml' },
    { name: 'eggplant', quantity: '1 small diced' },
    { name: 'bell peppers', quantity: '2 sliced' },
    { name: 'bamboo shoots', quantity: '100g' },
  ],
  instructions: [
    'Heat oil in a pan and fry curry paste for 1 minute',
    'Add coconut milk and bring to a simmer',
    'Add tofu, eggplant, peppers, and bamboo shoots',
    'Cook for 10-15 minutes until vegetables are tender',
    'Serve with jasmine rice',
  ],
  prepTime: 30,
  difficulty: 'medium',
  tags: ['thai', 'vegan', 'curry'],
  imageUrl: 'https://plus.unsplash.com/premium_photo-1713089366140-814130d69933?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1170',
},
{
  _id: new mongoose.Types.ObjectId('00000000000000000000000b'),
  name: 'Classic Caesar Salad',
  ingredients: [
    { name: 'romaine lettuce', quantity: '2 heads chopped' },
    { name: 'parmesan cheese', quantity: '50g grated' },
    { name: 'croutons', quantity: '1 cup' },
    { name: 'anchovies', quantity: '2 fillets' },
    { name: 'lemon juice', quantity: '2 tbsp' },
    { name: 'olive oil', quantity: '1/2 cup' },
  ],
  instructions: [
    'Make dressing by blending anchovies, lemon juice, and olive oil',
    'Toss chopped romaine with dressing',
    'Add parmesan cheese and croutons',
    'Serve immediately to maintain crispness',
  ],
  prepTime: 20,
  difficulty: 'easy',
  tags: ['salad', 'classic', 'vegetarian'],
  imageUrl: 'https://images.unsplash.com/photo-1725030660031-585ea459d55f?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=687',
},
{
  _id: new mongoose.Types.ObjectId('00000000000000000000000c'),
  name: 'Lemon Garlic Shrimp Pasta',
  ingredients: [
    { name: 'shrimp', quantity: '300g peeled' },
    { name: 'linguine pasta', quantity: '250g' },
    { name: 'garlic', quantity: '4 cloves minced' },
    { name: 'lemon', quantity: '2 zested and juiced' },
    { name: 'white wine', quantity: '100ml' },
    { name: 'parsley', quantity: '1/4 cup chopped' },
  ],
  instructions: [
    'Cook pasta according to package directions',
    'In a pan, sauté garlic until fragrant',
    'Add shrimp and cook until pink',
    'Add white wine and lemon juice, reduce by half',
    'Toss with pasta and lemon zest',
    'Garnish with parsley and serve',
  ],
  prepTime: 25,
  difficulty: 'medium',
  tags: ['seafood', 'pasta', 'lemon'],
  imageUrl: 'https://plus.unsplash.com/premium_photo-1707935175468-46bec1df8fc3?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1172',
},
{
  _id: new mongoose.Types.ObjectId('00000000000000000000000d'),
  name: 'Chocolate Chip Cookies',
  ingredients: [
    { name: 'butter', quantity: '200g softened' },
    { name: 'brown sugar', quantity: '150g' },
    { name: 'white sugar', quantity: '100g' },
    { name: 'eggs', quantity: '2' },
    { name: 'vanilla extract', quantity: '1 tsp' },
    { name: 'flour', quantity: '300g' },
    { name: 'chocolate chips', quantity: '200g' },
  ],
  instructions: [
    'Preheat oven to 350°F (175°C)',
    'Cream butter and sugars until light and fluffy',
    'Add eggs and vanilla, mix well',
    'Combine flour and baking soda, add to wet ingredients',
    'Fold in chocolate chips',
    'Drop by spoonfuls onto baking sheet, bake for 10-12 minutes',
  ],
  prepTime: 30,
  difficulty: 'easy',
  tags: ['cookies', 'dessert', 'baking'],
  imageUrl: 'https://plus.unsplash.com/premium_photo-1725384940713-45cdbbb49d94?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1170',
},
{
  _id: new mongoose.Types.ObjectId('00000000000000000000000e'),
  name: 'Greek Yogurt Parfait',
  ingredients: [
    { name: 'greek yogurt', quantity: '300g' },
    { name: 'granola', quantity: '100g' },
    { name: 'mixed berries', quantity: '1 cup' },
    { name: 'honey', quantity: '2 tbsp' },
    { name: 'almonds', quantity: '30g chopped' },
  ],
  instructions: [
    'In a glass, layer 1/3 of yogurt',
    'Add 1/3 of granola and berries',
    'Drizzle with honey',
    'Repeat layers twice more',
    'Top with chopped almonds',
    'Serve immediately or chill',
  ],
  prepTime: 10,
  difficulty: 'easy',
  tags: ['breakfast', 'healthy', 'no-cook'],
  imageUrl: 'https://plus.unsplash.com/premium_photo-1663855531713-836d43edde85?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=764',
},
{
  _id: new mongoose.Types.ObjectId('00000000000000000000000f'),
  name: 'Turkey Meatballs with Marinara',
  ingredients: [
    { name: 'ground turkey', quantity: '500g' },
    { name: 'breadcrumbs', quantity: '1 cup' },
    { name: 'egg', quantity: '1' },
    { name: 'parmesan cheese', quantity: '50g grated' },
    { name: 'marinara sauce', quantity: '500ml' },
    { name: 'parsley', quantity: '2 tbsp chopped' },
  ],
  instructions: [
    'Mix turkey, breadcrumbs, egg, parmesan, and parsley',
    'Form into meatballs',
    'Brown meatballs in a skillet',
    'Add marinara sauce and simmer for 20 minutes',
    'Serve with spaghetti or crusty bread',
  ],
  prepTime: 40,
  difficulty: 'medium',
  tags: ['italian', 'protein', 'oven'],
  imageUrl: 'https://plus.unsplash.com/premium_photo-1712598971951-0169ec4e7037?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=687',
},
{
  _id: new mongoose.Types.ObjectId('000000000000000000000010'),
  name: 'Mango Sticky Rice',
  ingredients: [
    { name: 'glutinous rice', quantity: '200g' },
    { name: 'mango', quantity: '2 ripe' },
    { name: 'coconut milk', quantity: '400ml' },
    { name: 'sugar', quantity: '100g' },
    { name: 'salt', quantity: '1/4 tsp' },
  ],
  instructions: [
    'Soak rice for 4 hours, then steam until tender',
    'Heat coconut milk with sugar and salt',
    'Pour half over rice, let sit for 10 minutes',
    'Slice mango cheeks thinly',
    'Serve rice topped with mango and remaining coconut sauce',
  ],
  prepTime: 30,
  difficulty: 'medium',
  tags: ['thai', 'dessert', 'tropical'],
  imageUrl: 'https://images.unsplash.com/photo-1711161988375-da7eff032e45?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1170',
},
{
  _id: new mongoose.Types.ObjectId('000000000000000000000016'),
  name: 'Watermelon Feta Salad',
  ingredients: [
    { name: 'watermelon', quantity: '500g cubed' },
    { name: 'feta cheese', quantity: '150g crumbled' },
    { name: 'red onion', quantity: '1/4 thinly sliced' },
    { name: 'mint leaves', quantity: '1/4 cup chopped' },
    { name: 'olive oil', quantity: '2 tbsp' },
    { name: 'lime juice', quantity: '1 tbsp' },
  ],
  instructions: [
    'Combine watermelon cubes and crumbled feta',
    'Add sliced red onion and chopped mint',
    'Drizzle with olive oil and lime juice',
    'Toss gently to combine',
    'Season with salt and pepper to taste',
    'Serve chilled',
  ],
  prepTime: 15,
  difficulty: 'easy',
  tags: ['salad', 'summer', 'refreshing'],
  imageUrl: 'https://images.unsplash.com/photo-1690921349852-7694d2b2c447?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=687',
},
{
  _id: new mongoose.Types.ObjectId('000000000000000000000017'),
  name: 'Baked Ziti',
  ingredients: [
    { name: 'ziti pasta', quantity: '400g' },
    { name: 'marinara sauce', quantity: '500ml' },
    { name: 'ricotta cheese', quantity: '250g' },
    { name: 'mozzarella cheese', quantity: '300g shredded' },
    { name: 'parmesan cheese', quantity: '50g grated' },
    { name: 'fresh basil', quantity: '1/4 cup chopped' },
  ],
  instructions: [
    'Preheat oven to 375°F (190°C)',
    'Cook ziti according to package directions',
    'Mix cooked ziti with marinara and ricotta',
    'Layer half in baking dish, top with half mozzarella',
    'Repeat layers, top with parmesan',
    'Bake for 25-30 minutes until bubbly and golden',
  ],
  prepTime: 50,
  difficulty: 'medium',
  tags: ['italian', 'baked', 'pasta'],
  imageUrl: 'https://images.unsplash.com/photo-1743324653833-98321dc52f58?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1171',
},
{
  _id: new mongoose.Types.ObjectId('000000000000000000000018'),
  name: 'Peanut Butter Banana Smoothie',
  ingredients: [
    { name: 'banana', quantity: '1 frozen' },
    { name: 'peanut butter', quantity: '2 tbsp' },
    { name: 'milk', quantity: '200ml' },
    { name: 'honey', quantity: '1 tbsp' },
    { name: 'ice cubes', quantity: '4' },
    { name: 'yogurt', quantity: '100g optional' },
  ],
  instructions: [
    'Add all ingredients to blender',
    'Blend until smooth and creamy',
    'Adjust sweetness with additional honey if needed',
    'Pour into glass and serve immediately',
  ],
  prepTime: 5,
  difficulty: 'easy',
  tags: ['smoothie', 'breakfast', 'quick'],
  imageUrl: 'https://plus.unsplash.com/premium_photo-1701210419479-e6b2e6038456?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=687',
},
{
  _id: new mongoose.Types.ObjectId('000000000000000000000019'),
  name: 'Chicken Shawarma Wraps',
  ingredients: [
    { name: 'chicken breast', quantity: '400g sliced' },
    { name: 'pita bread', quantity: '4' },
    { name: 'yogurt', quantity: '200g' },
    { name: 'garlic', quantity: '2 cloves minced' },
    { name: 'cucumber', quantity: '1 grated' },
    { name: 'shawarma spice', quantity: '2 tbsp' },
  ],
  instructions: [
    'Marinate chicken in shawarma spice for 1 hour',
    'Cook chicken in skillet until golden',
    'Mix yogurt, garlic, and cucumber for sauce',
    'Warm pita bread',
    'Fill with chicken and yogurt sauce',
    'Serve with pickles or hot sauce',
  ],
  prepTime: 30,
  difficulty: 'medium',
  tags: ['middle-eastern', 'wrap', 'protein'],
  imageUrl: 'https://images.unsplash.com/photo-1621334954920-9fc5f5490401?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=687',
},
{
  _id: new mongoose.Types.ObjectId('00000000000000000000001a'),
  name: 'Blueberry Cheesecake Bars',
  ingredients: [
    { name: 'graham crackers', quantity: '200g crushed' },
    { name: 'butter', quantity: '100g melted' },
    { name: 'cream cheese', quantity: '500g softened' },
    { name: 'sugar', quantity: '150g' },
    { name: 'eggs', quantity: '2' },
    { name: 'blueberries', quantity: '200g fresh' },
  ],
  instructions: [
    'Preheat oven to 350°F (175°C)',
    'Mix graham cracker crumbs with melted butter, press into pan',
    'Bake crust for 10 minutes, cool',
    'Beat cream cheese with sugar, add eggs',
    'Pour over crust, scatter blueberries on top',
    'Bake for 35-40 minutes, chill before cutting',
  ],
  prepTime: 60,
  difficulty: 'medium',
  tags: ['dessert', 'baking', 'cheesecake'],
  imageUrl: 'https://images.unsplash.com/photo-1744612190402-9e14a70a7a4e?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1170',
},
{
  _id: new mongoose.Types.ObjectId('00000000000000000000001b'),
  name: 'Shrimp Fried Rice',
  ingredients: [
    { name: 'shrimp', quantity: '200g peeled' },
    { name: 'cooked rice', quantity: '2 cups' },
    { name: 'mixed vegetables', quantity: '1 cup' },
    { name: 'soy sauce', quantity: '3 tbsp' },
    { name: 'green onions', quantity: '2 chopped' },
    { name: 'egg', quantity: '1 beaten' },
  ],
  instructions: [
    'Heat oil and scramble egg, set aside',
    'Cook shrimp until pink, set aside',
    'Stir-fry vegetables until crisp-tender',
    'Add rice and cook until heated through',
    'Add shrimp, egg, soy sauce, and green onions',
    'Stir-fry for 2 minutes and serve',
  ],
  prepTime: 20,
  difficulty: 'easy',
  tags: ['chinese', 'seafood', 'quick'],
  imageUrl: 'https://plus.unsplash.com/premium_photo-1661610605309-77feabcc8772?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1074',
},
];

const seedDB = async () => {
  try {
    await connectDB();
    await Recipe.deleteMany({});
    await Recipe.insertMany(recipes);
    console.log('Database seeded');
    process.exit(0);
  } catch (error) {
    console.error('Seeding error:', error);
    process.exit(1);
  }
};

seedDB();